Adding interior car shots for X and SC2
codetricity/theta_client_bitrate pull request #4
Opened 2023-06-28 22:49 UTC by jcasman

Created table to easily show off full images from car interior. It may not be good for page performance. (Too many images, loads slowly.)

2023-06-29 00:12 UTC, codetricity requested changes
put in ./test_images. modify file name to show bitrate. 

Example: R0010155-5M.JPG  indicates 5 megabit bitrate.


![image](https://github.com/codetricity/theta_client_bitrate/assets/5799860/b5dbfa08-6593-4121-8dcd-ac39f5c558d4)

2023-06-29 00:14 UTC, codetricity requested changes

2023-06-29 00:14 UTC, codetricity commented on README.md
> +| 20,971,520 | 21.4MB |![X-1M-nohdr](readme_assets/R0010183.JPG) |
put in the folder project/test_images/X /

2023-06-29 16:02 UTC, jcasman commented
Updated, please review and merge

2023-06-30 15:52 UTC, codetricity approved these changes

2023-06-30 15:52 UTC, merged